# Generated by Django 4.1.6 on 2023-02-08 04:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
                ('size', models.FloatField(blank=True, verbose_name='Tamaño')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('status', models.CharField(choices=[('A', 'Aceptado'), ('I', 'Iniciado'), ('T', 'En tránsito'), ('E', 'Entregado')], default='I', max_length=10, null=True, verbose_name='Estatus')),
                ('email_receiver', models.EmailField(default='', max_length=254, verbose_name='Correo')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('A', 'Aceptado'), ('I', 'Iniciado'), ('T', 'En tránsito'), ('E', 'Entregado')], default='I', max_length=10, null=True, verbose_name='Estatus')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='apiTracking.package', verbose_name='paquete')),
            ],
            options={
                'db_table': 'tracking',
            },
        ),
    ]
